project:
  type: website

jupyter:
  execute:
    execute_notebooks: false

website:
  title: "N. V. Decio"
  navbar:
    background: primary
    search: true

    right:
      - href: index.qmd
        text: Home
      - href: Portfolios.qmd
        text: Portfolio
      - href: Trainings.qmd
        text: Trainings
      - about.qmd 
  page-footer: 
    left: "Copyright 2025, Neil Vince Decio" 
    right: 
      - icon: github
        href: https://github.com/envicdus/Data_Analysis/tree/main
      - icon: linkedin
        href: https://www.linkedin.com/in/nvddecio/ 
  back-to-top-navigation: true



format:
  html:
    grid:
      sidebar-width: 0px
      body-width: 1100px
      margin-width: 200px
    theme:
      dark: darkly
      light: flatly

    toc: true
    
execute:
  freeze: True