project:
  type: website

website:
  title: "N. V. Decio"
  navbar:
    background: primary
    search: true

    right:
      - text: "Home"
        href: index.qmd
      - Portfolios.qmd
      - Trainings.qmd
      - Resume.qmd 

format:
  html:
    theme:
      light: brand
    css: styles.css
    toc: true
    