---
Author: "Neil Vince Decio"
title: "My Portfolio"
---



Hi! I am Neil, a Chemist transitioning into Data Analysis with a strong foundation in analytical thinking and problem-solving. With experience in creating dashboards, data visualization, and Python development, I bring a unique blend of scientific expertise and technical skills to data-driven decision-making. I have passed SQL certification exams on both DataCamp and HackerRank, demonstrating my proficiency in querying and managing data. Additionally, I have experience teaching college-level subjects, showcasing my ability to communicate complex concepts effectively.

I am proficient in Python, SQL, and Excel and enjoy building insightful dashboards that turn raw data into actionable intelligence. I also have experience developing Python applications as a hobby, reinforcing my programming and automation skills.

Beyond my technical abilities, I am passionate about continuous learning and personal growth. I am currently learning German while also learning more about data analysis like making personal projects, further enhancing my adaptability and analytical mindset. I also enjoy reading, jogging, running, and volunteering, which help me stay engaged and balanced. As I transition into a full-time Data Analyst role, I am eager to apply my skills to real-world business challenges, leveraging data to drive impactful decisions.

My resume in pdf.

This is a repository to showcase skills, share projects and track my progress in Data Analytics / Data Science related topics.

